version: '3'

services: 
    pythonDevelopContainer: 
        image: python:3.8-buster
        volumes: 
            - ../../Practice:/pysrc
        environment: 
            LANG ja_JP: UTF-8
            LANGUAGE ja_JP: ja
            LC_ALL ja_JP: UTF-8
        ports: 
            - 3000:3000
        tty: true